let codeLookupDay = {
  0: "sunny",
  1: "sunny",
  2: "cloudy",
  3: "overcast",
  45: "fog",
  48: "fog",
  51: "drizzle-light",
  53: "drizzle-dense",
  55: "drizzle-dense",
  56: "freezing-drizzle",
  57: "freezing-drizzle",
  61: "rain-slight",
  63: "rain",
  65: "heavy-rain",
  66: "sleet-hail",
  67: "freezing-rain-heavy",
  71: "snow",
  73: "snow",
  75: "snow",
  77: "snow-grains",
  80: "rain-and-sun",
  81: "rain-and-sun",
  82: "rain-and-sun",
  85: "snow",
  86: "snow",
  95: "thunder-slight",
  96: "thunder-rain",
  99: "thunder-rain-heavy",
};

let codeLookupNight = {
  0: "night-fullmoon",
  1: "night-fullmoon",
  2: "night-fullmoon",
  3: "night-overcast-fullmoon",
  45: "night-fog-fullmoon",
  80: "night-rain-moon-heavy",
  81: "night-rain-moon-heavy",
  82: "night-rain-moon-heavy",
};
